# Generated by Django 4.2.4 on 2023-08-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auction',
            table='auction',
        ),
    ]
