# Generated by Django 4.2.4 on 2023-08-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_auction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balanceoperation',
            table='balanceoperation',
        ),
        migrations.AlterModelTable(
            name='cityauction',
            table='cityauction',
        ),
        migrations.AlterModelTable(
            name='correspondence',
            table='correspondence',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='placedelivery',
            table='placedelivery',
        ),
        migrations.AlterModelTable(
            name='transportation',
            table='transportation',
        ),
    ]
