# Generated by Django 4.2.4 on 2023-09-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_alter_services_ser_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table='services',
        ),
    ]
