# Generated by Django 4.2.4 on 2023-09-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_alter_services_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(to='logistic.services'),
        ),
    ]
