# Generated by Django 4.2.4 on 2023-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_remove_order_service_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='correspondence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
